In [1]:
import pandas as pd
import scipy.sparse as sp
import numpy as np
from Utils.recsys2022DataReader import *

In [2]:
types = pd.read_csv('Input/data_ICM_type.csv')
types = types.drop(columns=['data'], axis=1)
types = types.rename(columns={'feature_id': 'type'})


typesFiltered = types[types['item_id'] <= 24506]
itemsID = typesFiltered['item_id'].to_numpy()
typesArray = typesFiltered['type'].to_numpy()
ICM = np.zeros((24507, 7), dtype=float)

In [3]:
itemsID

array([    0,     1,     2, ..., 24504, 24505, 24506])

In [4]:
typesArray

array([1, 3, 4, ..., 1, 4, 1])

In [5]:
typesFiltered

item_id  type
0            0     1
1            1     3
2            2     4
3            3     1
4            4     3
...        ...   ...
19625    24502     1
19626    24503     4
19627    24504     1
19628    24505     4
19629    24506     1

[19630 rows x 2 columns]

In [6]:
for x in range(len(itemsID)):
    ICM[itemsID[x]][typesArray[x]-1] = 1

In [7]:
ICM

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])