In [1]:
import pandas as pd
import scipy.sparse as sp
import numpy as np
from Utils.recsys2022DataReader import *

In [2]:
datasetTrain = load_FinalURMTrainInit()

In [3]:
datasetTrain

<41629x24507 sparse matrix of type '<class 'numpy.float64'>'
	with 1321444 stored elements in Compressed Sparse Row format>

In [4]:
datasetTrain.data

array([1.  , 1.  , 1.  , ..., 1.  , 1.25, 1.25])

In [10]:
binaryDataset = datasetTrain
binaryDataset.data

array([1.  , 1.  , 1.  , ..., 1.  , 1.25, 1.25])

In [11]:
binaryDataset.data[0]

1.0

In [12]:
for i in range(len(binaryDataset.data)):
    binaryDataset.data[i] = 1.0

In [13]:
binaryDataset.data

array([1., 1., 1., ..., 1., 1., 1.])